### ISSUE TITLE
CORE deposit takedown options

### ISSUE THREAD

**Issue by ericknappe** [MESH-Research/knowledge-commons-works#164]
We should discuss current deposit takedown practices and options and the impacts. We should look at modifications to the process and future possible improvements. "Soft removal" in particuar, which is new, should be reviewed.

CORE removal options

Embargo

Download becomes unavailable
DOI remains public
DOI metadata remains
CORE landing page remains on site
Deposited file remains in repo
Deposit remains searchable
Author profile entry remains
Author ORCID entries remain

Soft removal

DOI made non-public
BP activities removed ??
Solr document removed ??
HC URL redirected to /deposits/removed
Author profile entries no longer available
Author ORCID entries no longer resolve

Full removal

DOI made non-public
DOI metadata removed
BP activities removed
Solr document removed
Fedora objects (2) removed
Uploaded file removed from HC directory
HC URL redirected to /deposits/removed
WP custom posts (2) removed
Author profile entries no longer available
Author ORCID entries no longer resolve

**Comment by bjr70** [comment]
I'm transferring this issue over to the KC repository. We should consider this as we implement Invenio.

**Comment by bjr70** [comment]
Moved to new epic in cleanup.
