### ISSUE TITLE
CLI script to process a list of files with best libraries and output JSON

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-works#316]

**Comment by monotasker** [comment]
- start with JSON list of filenames
- start with those files in a central download folder
- read the list of files
- for each, recognize file type, open and extract file, write text into JSON file as one object

**Comment by koutiany** [comment]
Created a new .md file to store code for creating cli.
https://github.com/MESH-Research/nlp-ml-repo/blob/main/tutorial2-cli.md

**Comment by koutiany** [comment]
I wrote a roadmap for the coming semester with tangible outcomes. The roadmap can be found in the same github repo, under "workflow-overview.md." https://github.com/MESH-Research/nlp-ml-repo/tree/main

**Comment by koutiany** [comment]
Miro board with more updates see here: https://miro.com/app/board/uXjVN6Ju0aY=/?share_link_id=481066257271
