### ISSUE TITLE
High-level description of what topic modelling is doing

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-works#371]

**Comment by koutiany** [comment]
I am now able to explain LDA TM. I will schedule a 30 minutes meeting with Ian next week (1/29) to report back.
Here are the list of things I want to go over:
- LDA TM
What I don't think I am able to explain: 
- Math behind it (e.g. )

*** Two important papers from Blei: I didn't read the math part.
https://www.jmlr.org/papers/volume3/blei03a/blei03a.pdf
https://www.cs.columbia.edu/~blei/papers/Blei2012.pdf

**Comment by koutiany** [comment]
Also just want to put Gensim's documentation here for future references: https://radimrehurek.com/gensim/auto_examples/index.html#
