### ISSUE TITLE
CLI to extract and store records prior to cleaning

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-works#403]
1. CLI data gathering pipeline
  1.1 Api request to api/records [do this in memory]
  1.2 Iterate over hits [try catch, log error, there is one py lib that can be used]
      1.2.1 Collect record id, language, file names/ids
      1.2.2 Download files via API (api/records/{id}/files/content)
      1.2.3 Extract textual data from files
               ***Use appropriate logic for file type
      1.2.4 Store textual data & metadata in db/csv
               item a. record id
               item a. language
               item a. text
      1.2.5 [at the same time] log success (rec_ids)
2. Storage format options: 
  cvs?
  Sqlite with SQLAlchemy???
3. Cleaning language data (in case invenio's judgement is not accurate)?
   Use ChatGPT???

**Comment by koutiany** [comment]
More detailed discussions and how we got here can be found in this google doc: https://docs.google.com/document/d/1W2Y-qTqWRg8Oow22Oc4rjuFmi_EVinuVXe6Rp22knjA/edit

**Comment by koutiany** [comment]
1/30/2024: Completed the following with a sample set of 500
1.1 Api request to api/records [do this in memory]
1.2 Iterate over hits [try catch, log error, there is one py lib that can be used]
1.2.1 Collect record id, language, file names/ids
1.2.2 Download files via API (api/records/{id}/files/content)

**Comment by koutiany** [comment]
Now I have a script that deals with:
1.2.3 + 1.2.4 Store textual data & metadata in db/csv + 1.2.5 + 2
Script is uploaded to [Github repo](https://github.com/MESH-Research/nlp-ml-repo), under the name "apiinvenio-updated.py" (with fake api key).
Here are my updates: 
1. Currently running the script to access all files, log the errors. Pdf. type file is dominant. I am seeing minor issues with downloading (2/3000). 
2. Multilingual related questions will be addressed in a later stage.
3. I don't see the Error message in item 4. in the previous post anymore.
