### ISSUE TITLE
Migrated users in collections appearing with bad names

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/knowledge-commons-works#583]
**Describe the bug**
Admins is groups are being migrated as things like "knowledge-Commons-zwh" and are not viewable by recognizable name.

**Expected behavior**
Users should be listed by name.

**Screenshots**
<img width="1333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0VIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7e21f6b5b0e60fdf96339abd81e6e94054bc74b/Screenshot%202024-07-24%20at%202.07.52%E2%80%AFPM.png" alt="Screenshot 2024-07-24 at 2.07.52 PM.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by monotasker** [comment]
This will be resolved automatically once the users full names are imported from KC. That should happen automatically when they log in, but there may be an issue. I'll check before launch

**Comment by bjr70** [comment]
Stop looking! We’ll sort it on the 5th. Go back to having a good time.

**Comment by monotasker** [comment]
This should be resolved as soon the user has a readable name imported from their KC account. The username has to use that format internally in KCWorks, but it is not displayed if the user has a full readable name. There may be an issue on prod with user profile data not being imported automatically, and so the full names not being available for display. I'll resolve it before launch day.

**Comment by monotasker** [comment]
2024-08-13 - Encountering weird situation with hctester80@gmail.com where saml login returns different username than the one actually used for that login in kc (kelly4200 vs hctester80)

**Comment by monotasker** [comment]
2024-08-14 - Added a cli utility to manually update remote user data to allow for testing
2024-08-14 - Confirmed that user names display correctly when the fullname data is present (from remote)

**Comment by monotasker** [comment]
2024-08-16 Fixed indexing problem
