### ISSUE TITLE
Works with .doc / .docx attachments crash viewer / cannot be downloaded

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/knowledge-commons-works#588]
**Describe the bug**

CORE deposits with docx or doc attachments failed to migrate. (Or I have been unable to find examples of successful migration.)

**To Reproduce**

1. SSH to kcworks-prod
2. Connect to the UI container: `docker exec -it 4028a614fad1 /bin/bash`
3. `cd /opt/invenio/var/import_data/import_files`
4. `ls *.doc` / `ls *.docx` Eg. `o_1a40ns08si5p1buq1koc1eai1rb67.doc.applied_blake_miltons_response_to_empire.doc`
5. Find corresponding CORE deposit (usually by intuiting deposit title from filename) Eg. [Applied Blake: Milton's Response to Empire](https://hcommons.org/deposits/item/mla:357/)
6. Search for deposit on Works. Eg. https://works.hcommons.org/records/eak7n-gxp03 
7. Click on deposit
8. Viewer does not appear
9. Click on Download
10. Goes to: https://works.hcommons.org/records/undefined/undefined?download=1

Example .docx : https://hcommons.org/deposits/item/mla:103/ / https://works.hcommons.org/records/ewxqw-1hm19

Deposits that seem not to have migrated at all:

- https://hcommons.org/deposits/item/hc:57493/
- https://hcommons.org/deposits/item/hc:57723/
- https://hcommons.org/deposits/item/mla:955/
- https://hcommons.org/deposits/item/mla:959/
- https://hcommons.org/deposits/item/hc:32859/
- https://hcommons.org/deposits/item/hc:32855/

**Expected behavior**

The work would be viewable and downloadable

**Comment by monotasker** [comment]
The files have migrated properly and can be downloaded directly with api calls. The issue is that the links on the detail page are wrong. This is happening somewhere in the UI data handling, since the 'link' values coming from the back end are correct.
