### ISSUE TITLE
Provide a path to register for the Commons from Works

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/knowledge-commons-works#624]
**Is your feature request related to a problem? Please describe.**
If you find Works before you find KC and you decide you want to post some of your work there's no clear way to register. When you click "log in" it just takes you to the login methods page. There's no clear path to registration from Works.

**Describe the solution you'd like**
Provide a button in addition to log in that says "Create an Account" and points to https://hcommons.org/membership/ or something like that. 

**Describe alternatives you've considered**
No real alternatives. We don't have a page to point to that offers both options. 

**Additional context**
I expect that we will get users who find Works first and are unfamiliar with the Commons.

**Comment by monotasker** [comment]
Added a register link to login page
