### ISSUE TITLE
Import records that were missing from export

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-works#655]

**Comment by bjr70** [comment]
We still have a number of missing deposits that aren't showing up. Are these in the manual update list? 
https://doi.org/10.17613/6q77-ae96
https://hcommons.org/deposits/item/hc:43707/
https://works.hcommons.org/records/gm8ty-j6234
https://hcommons.org/deposits/item/hc:65891/
https://hcommons.org/deposits/item/hc:65889/

EVERY item at https://openiberiaamerica.hcommons.org/. I will try to pull the DOIs for those on Monday.

**Comment by monotasker** [comment]
It's difficult to know what to do with these at the moment. I was still importing records all day and just finished. So I'm not sure when you checked last

**Comment by bjr70** [comment]
Don't do anything until I check them next week. They may be resolved.
