### ISSUE TITLE
User missing deposit on profile - user is in the editor role, Mike says plugin pulling from "creators"

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/knowledge-commons-works#659]
I've got a user who is looking for this deposit on his profile https://works.hcommons.org/records/gm8ty-j6234 profile https://hcommons.org/members/ccooijmans/ but he's listed as an editor not an author, he's an editor. Is editor in the creators list or contributors? Ideally it should show up.

**Comment by monotasker** [comment]
Editors are in the "creators" list and he's listed in "creators" for that record. The record shows up in an api search for metadata.creators.person_or_org.name:"Cooijmans, Christian". So I think everything is working fine on the Works end.

You can see the record show up in an api request to https://works.hcommons.org/api/records?q=metadata.creators.person_or_org.name%3A%22Cooijmans%2C%20Christian%22&l=list&p=1&s=10&sort=bestmatch

**Comment by monotasker** [comment]
I think there must be something happening on the WP end if it's not being displayed on his profile

**Comment by bjr70** [comment]
@mikethicke can you take a look at this/

**Comment by monotasker** [comment]
After talking with Mike, we realized that the user's hc id isn't present in the creator information for that record. I need to investigate why it didn't get added during the serialization/migration. Should be a relatively easy fix, but I should also run through the other migrated records for the same issue.

**Comment by monotasker** [comment]
Turns out the issue is that the user uploaded this work and didn't include their KC username. (It's autopopulated if they use "add self"). So the solution is for them to go in and add it on their creator item on the upload/edit form. Under identifiers they add a new identifier of the type "KC id".
