### ISSUE TITLE
Missing downloads in download count

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/knowledge-commons-works#660]
Hey Ian,

Justin is saying that this deposit - https://works.hcommons.org/records/z52r7-dw349 had about 260 downloads and now only has 96. Can we check into this? Not sure how to validate that. Can you look into it when you get the chance?

**Comment by bjr70** [comment]
As of May 2024 there were 194 downloads per this sheet - https://docs.google.com/spreadsheets/d/1iuLoVA0QpjBzBkH-To-3j2u049HtmaLhHu9VNU2OHoI/edit?usp=sharing

**Comment by monotasker** [comment]
The metadata export from CORE for this one had 0 views and 0 downloads. The 4 views (and 96 downloads!!?) must all have been since launch. So the question here is why the figure exported from CORE seems to be wrong...

**Comment by monotasker** [comment]
We found an issue with the view and download numbers in the latest export. It's been corrected in a new export and I'll try to update all of the numbers tomorrow
